# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zview < Formula
  desc "Fast, lightweight, read-only PDF viewer"
  homepage "https://github.com/kyaoi/zview"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kyaoi/zview/releases/download/v1.2.2/zview_Darwin_x86_64.tar.gz"
      sha256 "a5da1541c42d57738daf550b0923eb862ee1f417f294dd247685e00efbc03f31"

      define_method(:install) do
        bin.install "zview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kyaoi/zview/releases/download/v1.2.2/zview_Darwin_arm64.tar.gz"
      sha256 "730da614320a194a2067881515b43c401342633814166f747f883720264a64ae"

      define_method(:install) do
        bin.install "zview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyaoi/zview/releases/download/v1.2.2/zview_Linux_x86_64.tar.gz"
      sha256 "3135f6485006e1618ab3a40887833d54e5aaa6ec7f059fe4d9c22d5625c554dd"
      define_method(:install) do
        bin.install "zview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kyaoi/zview/releases/download/v1.2.2/zview_Linux_arm64.tar.gz"
      sha256 "64c0a36d192e4e44df9f40f468a20fddaa9457c8747b6effaead8ae61bcbc929"
      define_method(:install) do
        bin.install "zview"
      end
    end
  end
end
